config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  controller :sessions do
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :movies, only: [:new, :create, :edit, :update]

  resources :profile, only: [:index]
  resources :password, only: [:edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user

  delegate :email, to: :user, allow_nil: true, prefix: true

  validates :youtube_url, :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :password, presence: true, length: { minimum: 8 }, confirmation: false, on: :create
  validates :password, presence: true, length: { minimum: 8 }, on: :update

  has_secure_password

  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, with: :exception
  before_action :authorize
  skip_before_filter :verify_authenticity_token

  private

  def authorize
    redirect_to root_path, notice: "Please Login or Register" unless User.find_by(id: session[:user_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:edit, :update]

  def new
    @movie = Movie.new
  end

  def create
    success, messages = MovieCreator.new(params: movie_params, user_id: session[:user_id]).perform
    flash.merge!(messages)
    if success
      redirect_to root_path
    else
      @movie = Movie.new(movie_params)
      render :new
    end
  end

  def edit
    redirect_to root_path if @movie.user_id != session[:user_id]
  end

  def update
    success, messages = MovieCreator.new(params: movie_params, user_id: session[:user_id], movie: @movie).perform
    flash.merge!(messages)
    if success
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_movie
    @movie ||= Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:youtube_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authorize

  def index
    @movies = Movie.order('created_at desc').page(params[:page])
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_index_path(@user), notice: "Your password has been updated."
    else
      render :edit
    end
  end

  private

  def set_user
    @user ||= User.find(session[:user_id])
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    @movies = @user.movies
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def create
    status, logged_in_data, messages = UserPerformer.new(user_params).perform
    if status
      create_success(logged_in_data)
    else
      create_failure(messages)
    end
  end

  def destroy
    session[:user_email] = session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def create_success(logged_in_data)
    session.merge!(logged_in_data)
    redirect_to root_path
  end

  def create_failure(messages)
    flash.now[:danger] = messages[:danger]
    @user = User.new(user_params)
    @movies = Movie.page(params[:page])
    render "pages/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.haml
- if flash.present?
  .ml-4.mr-4
    - flash.each do |type, msg|
      %div{ class: "alert alert-#{type}" }
        = msg

app/views/layouts/_footer.html.haml
%hr
%footer.container
  %p= "© 2019 - #{Date.current.year}, Chi Dang"
:javascript
  $( document).ready( function(){
      $('div.alert').not('.alert-danger').delay(3000).slideUp(300);
  });

app/views/layouts/_logged_in.html.haml
%nav.my-2.my-md-0.mr-md-3
  %span.p-2
    = link_to "Welcome #{session[:user_email]}", profile_index_path, {class: "text-light"}
  = link_to 'Share a movie', new_movie_path, { class: "p-2 ml-4 btn btn-primary" } 
  = link_to 'Logout', logout_path, { class: "p-2 ml-4 btn btn-danger" }

app/views/layouts/_login_form.html.haml
= form_for(:user, url: login_path, method: :post, html: { class: 'form-inline mt-2 mt-md-0'}) do |f|
  = f.text_field :email, class: 'form-control mr-sm-2 my-2', placeholder: 'Email'
  = f.password_field :password, class: 'form-control mr-sm-2 my-2', placeholder: 'Password'
  = f.submit 'Login / Register', class: 'btn btn-primary my-2'

app/views/layouts/_navigation.html.haml
.d-flex.flex-column.flex-md-row.p-3.px-md-4.mb-3.navbar-dark.bg-dark.border-bottom
  %h1.h2.my-0.mr-md-auto.font-weight-normal
    = link_to root_path, {class: "navbar-brand"} do
      = "#{icon('fas', 'home')} Funny Movies".html_safe
  .my-2.my-md-0.mr-md-3
    - if session[:user_email].present?
      = render 'layouts/logged_in'
    - else
      = render 'layouts/login_form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1'}
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Funny Movies
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    = render 'layouts/flash'
    %main.container.pb-4
      = yield
    = render 'layouts/footer'

app/views/movies/_edit_fields.html.haml
%fieldset.scheduler-border
  %legend.scheduler-border Update Youtube movie
  .form-group.row
    .col-sm-2
      = f.label :youtube_url, 'Youtube URL'
    .col-sm-10
      = f.text_field :youtube_url, class: 'form-control mr-sm-2', placeholder: 'e.g. https://www.youtube.com/watch?v=RRPp-qbKK6E'
  .form-group.row
    .col-sm-2
      = f.label :title, 'Title'
    .col-sm-10
      = f.text_field :title, class: 'form-control mr-sm-2'
  .form-group.row
    .col-sm-2
      = f.label :description, 'Description'
    .col-sm-10
      = f.text_area :description, class: 'form-control', rows: 10
  .form-group.row
    .col-sm-2
    .col-sm-10
      = f.submit 'Update', class: 'btn btn-primary btn-block'

app/views/movies/_form.html.haml
= form_for(movie) do |f|
  - if movie.errors.any?
    .ml-4.mr-4
      - movie.errors.full_messages.each do |message|
        %div{ class: "alert alert-danger" }
          = message
  - if movie.id.present?
    = render "edit_fields", movie: movie, f: f
  - else
    = render "share_fields", movie: movie, f: f

app/views/movies/_share_fields.html.haml
%fieldset.scheduler-border
  %legend.scheduler-border Share a Youtube movie
  .form-group.row
    .col-sm-2
      = f.label :youtube_url, 'Youtube URL'
    .col-sm-10
      = f.text_field :youtube_url, class: 'form-control mr-sm-2', placeholder: 'e.g. https://www.youtube.com/watch?v=RRPp-qbKK6E'
  .form-group.row
    .col-sm-2
    .col-sm-10
      = f.submit 'Share', class: 'btn btn-primary btn-block'

app/views/movies/edit.html.haml
.d-flex.justify-content-center
  .w-75
    = render 'form', movie: @movie

      

app/views/movies/new.html.haml
.d-flex.justify-content-center
  .w-75
    = render 'form', movie: @movie

app/views/pages/index.html.haml
- if @movies.count > 0
  - @movies.each do |movie|
    .row.mt-4
      .col-md-5.embed-responsive.embed-responsive-16by9
        %iframe.embed-responsive-item{ src: "https://www.youtube.com/embed/#{movie.youtube_video_id}?rel=0" }
      .col-md-7
        %h4.text-danger
          - if movie.user_id == session[:user_id]
            = link_to movie.title, edit_movie_path(movie.id)
          - else
            = movie.title

        %p= "Shared by: #{movie.user_email}"
        %p
          %strong Description
        %p=movie.description
  .mt-4= paginate @movies
- else
  %p Currently, don't have any movies available.

app/views/password/edit.html.haml
.d-flex.justify-content-center
  .w-75
    = form_for @user, url: password_path(@user) do |f|
      - if @user.errors.any?
        .ml-4.mr-4
          - @user.errors.full_messages.each do |message|
            %div{ class: "alert alert-danger" }
              = message
      .form-group.row
        .col-sm-4
          = f.label :password, 'Password'
        .col-sm-8
          = f.password_field :password, class: 'form-control mr-sm-2'
      .form-group.row
        .col-sm-4
          = f.label :password_confirmation, 'Confirm Password'
        .col-sm-8
          = f.password_field :password_confirmation, class: 'form-control mr-sm-2'
      
      .form-group.row
        .col-sm-4
        .col-sm-8
          = f.submit 'Update', class: 'btn btn-primary btn-block'  

      